title: "Curry Guinn"
description: "Teaching, research, and resources on the CU Boulder Applied Computer Science Post-Baccalaureate program"
url: "https://curryguinncspb.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

markdown: kramdown
permalink: /:categories/:title/
logo: /assets/images/headshot.jpg

minimal_mistakes_skin: "dark"

main:
  - title: "About"
    url: /about/
    
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false

collections:
  cspb:
    output: true
    permalink: /cspb/:path/

author:
  name: Curry Guinn
    links:
    - label: LinkedIn
      url: https://www.linkedin.com/in/curry-guinn-696685/
    - label: Google Scholar
      url: https://scholar.google.com/citations?user=Iwkx4qwAAAAJ&hl=en 

lang: en  
  